// Code generated by MockGen. DO NOT EDIT.
// Source: server/httpserver.go
//
// Generated by this command:
//
//	mockgen -source=server/httpserver.go -destination=mocks/server/mock_httpserver.go -package=mock_server
//

// Package mock_server is a generated GoMock package.
package mock_server
